version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:13.6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=newPassword
    ports:
      - '5438:5432'
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6375:6379'
    volumes:
      - ./cache:/data
volumes:
  postgres_db:
    driver: local
